### ISSUE TITLE
fix emeth jacket image

### ISSUE THREAD

**Issue by albno273** [nakaatsu118/denonbu-info#1]
## What to do

emeth のジャケットの上と左に白い 1px の線が入っており、黒背景のサイトに出すと見た目が微妙なのでどうにかしたい
https://images.microcms-assets.io/assets/d38aa34631f042429583e7175b99f633/53797b54a1f34f5585880771a4a6476b/asoes00097906.jpg?w=200

## other

いや公式提供の画像がこれなんじゃい！という話はある

**Comment by nakaatsu118** [comment]
元画像が微妙だったので差し替えましtあ

**Comment by albno273** [comment]
天才
